baseURL = ""
languageCode = "en-us"
title = "Northendlab | Blog Template"
theme = "northendlab light"
paginate = "5"
summaryLength = "10"
disqusShortname = ""
themesDir = "themes"
publishDir = "public"

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON" ]

[params]
home = "Home"
logo = "images/logo.svg"
author = "Themefisher"
description = "This is meta description"
google_tag_manager = ""
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/search/fuse.min.js"

[[params.plugins.js]]
link = "plugins/search/mark.js"

[[params.plugins.js]]
link = "plugins/search/search.js"

  [params.preloader]
  enable = true
  preloader = ""

  [params.search]
  enable = true

  [params.cookies]
  enable = true
  expire_days = 2

  [params.banner]
  bgImage = "images/banner/banner-bg.svg"
  title = "Hi, I'm John Smith Doe. <br> I help people make the  worlds best software"
  image = "images/banner/illustration.svg"

  [params.cta]
  enable = true
  image = "images/hugo-muscot.svg"
  title = "Get the best hugo templates"
  description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."

    [params.cta.button]
    enable = true
    label = "Visit Here"
    link = "https://gethugothemes.com/shop/"

  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-github"
  link = "#"

  [[params.social]]
  icon = "ti-linkedin"
  link = "#"

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.main]]
URL = "tools"
name = "tools"
weight = 2

[[menu.main]]
URL = "https://gethugothemes.com/products/northendlab/"
name = "Buy Premium"
weight = 2

[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
